apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: Project for observability applications
  sourceRepos:
    - https://github.com/marciorbr/gitops_aws_eks.git
  destinations:
    - namespace: observability
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Event'