adminUser: admin
adminPassword: adminPassword        
        
persistence:
    enabled: true
    size: 10Gi
    storageClassName: dynamic-efs-sc
service:
    type: NodePort

ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.customer.com.br
initChownData:
    enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.customer.local
        isDefault: false
        jsonData:
          maxLines: 1000
          derivedFields:
          - datasourceName: Tempo
            datasourceUid: Tempo
            matcherRegex: '\\"traceID\\":\\"([^\\"]+)\\"'
            name: traceID
            url: $$${__value.raw}